version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend-container
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
  
  frontend:
    build:
      context: ./frontend
    container_name: frontend-container
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: ["npm", "start"]
