export const TECHNOLOGY_COLORS = {
  // Frontend technologies (magenta)
  javascript: 'magenta',
  js: 'magenta',
  html: 'magenta',
  css: 'magenta',
  react: 'magenta',
  angular: 'magenta',
  vue: 'magenta',
  'React.JS': 'magenta',
  'reactjs': 'magenta',
  'typescript': 'magenta',
  'html': 'magenta',
  'css': 'magenta',
  'scss': 'magenta',
  'sass': 'magenta',


  // Backend technologies (green)
  python: 'green',
  java: 'green',
  cpp: 'green',
  node: 'green',
  'node.js': 'green',
  nodejs: 'green',
  express: 'green',
  django: 'green',
  flask: 'green',
  php: 'green',
  ruby: 'green',
  swift: 'green',
  kotlin: 'green',
  c: 'green',
  'C++': 'green',
  'c++': 'green',
  'cpp': 'green',
  'go': 'green',
  'golang': 'green',
  'nestjs': 'green',
  'spring': 'green',
  'spring boot': 'green',
  'laravel': 'green',
  'ruby on rails': 'green',
  'ror': 'green',
  'express.js': 'green',
  'expressjs': 'green',
  'flask': 'green',
  'django': 'green',
  'node.js': 'green',
  'nodejs': 'green',
  'php': 'green',
  'ruby': 'green',
  'swift': 'green',
  'kotlin': 'green',
  rust: 'green',


  // Add 'purple' for DB technologies
  sql: 'purple',
  mysql: 'purple',
  postgresql: 'purple',
  mongodb: 'purple',
  redis: 'purple',
  sqlite: 'purple',
  oracle: 'purple',
  mariadb: 'purple',
  cassandra: 'purple',
  'dynamodb': 'purple',
  postgres: 'purple',


  // AI/ML technologies (volcano)
  tensorflow: 'volcano',
  pytorch: 'volcano',
  ai: 'volcano',
  ml: 'volcano',
  llm: 'volcano',
  llms: 'volcano',
  'deep learning': 'volcano',
  'machine learning': 'volcano',
  'artificial intelligence': 'volcano',
  'natural language processing': 'volcano',
  'computer vision': 'volcano',
  'reinforcement learning': 'volcano',
  'generative ai': 'volcano',
  cv: 'volcano',
  nlp: 'volcano',


  // Cloud technologies (blue)
  aws: 'blue',
  azure: 'blue',
  gcp: 'blue',
  

};
